language: php
php:
  - 5.5.9
#  - 5.6
#  - 7.0
#  - hhvm
before_script:
  - travis_retry composer self-update
install:
  - composer install --prefer-source --no-interaction
script:
  - phpunit --coverage-clover=coverage.xml
  - vendor/bin/php-cs-fixer fix --dry-run
after_success:
  - bash <(curl -s https://codecov.io/bash)
